### ISSUE TITLE
[Question] SignInFormBloc.mapEventToState() issue

### ISSUE THREAD

**Issue by bohuz23** [ResoCoder/flutter-ddd-firebase-course#3]
Hi, I'm facing with next error: 

>error: The type 'Stream<SignInFormState>' implied by the 'yield' expression must be assignable to Stream\<Null\>

and it's appearing for every `state.copyWith()` call 
![image](https://user-images.githubusercontent.com/4972685/81182164-22452c80-8fb6-11ea-9232-4a6d6d29d591.png)

Any thoughts on it? 
I'm on Flutter v1.13.6 and Dart v2.8.0

**Comment by Teclys23** [comment]
Actually I have the same error, but if I run it anyway, the app is working pretty good.

**Comment by erkansahin** [comment]
The problem is about linting. You need to add the following code to the analysis.yaml file:
```
  strong-mode:
    implicit-casts: true

```
After the addition, the file should look like the following:

```
analyzer:
  strong-mode:
    implicit-casts: true
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
```


If you want to read more from the resource go to:
[analysis options](https://dart.dev/guides/language/analysis-options)
